# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-12 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffuse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BombTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bombtime', models.TimeField(blank=True, verbose_name='Conversation Time')),
            ],
        ),
    ]
